name: my_thai_star_flutter
description: The Flutter version of the Capgemini reference project My Thai Star.
version: 1.0.0+1

#for release:       flutter build apk --release

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_bloc: ^0.21.0
  equatable: ^0.6.1
  http: ^0.12.0+2
  badges: ^1.1.0
  country_icons: ^1.1.1
  page_transition: "^1.1.5"
  datetime_picker_formfield: any
  # Own Packages
  bool_bloc:
    path: ./packages/bool_bloc
  form_bloc:
    path: ./packages/form_bloc

  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter
    
  cupertino_icons: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/languages/